import { useEffect, useState } from 'react'
import { CalendarClock, Check, ChevronRight, CircleAlert, Clock3, Play, Plus, RefreshCw, RotateCcw, ShieldCheck, Workflow, X, Zap } from 'lucide-react'
import { approveAutomationRun, createAutomationWorkflow, getAutomationWorkspace, retryAutomationRun, runAutomation, setAutomationEnabled } from './api.js'

const EMPTY = { workflows: [], runs: [] }
const actionNames = { learning_cycle: 'Siklus pembelajaran agent', knowledge_health_check: 'Pemeriksaan knowledge index' }

function RunStatus({ status }) { return <span className={`run-status run-status--${status.toLowerCase()}`}><i />{status.replaceAll('_', ' ')}</span> }

function WorkflowBuilder({ onClose, onCreated }) {
  const [form, setForm] = useState({ name: '', action: 'knowledge_health_check', interval_minutes: 60, approval_required: true })
  const [state, setState] = useState({ status: 'idle', message: '' })
  async function submit(event) {
    event.preventDefault(); setState({ status: 'saving', message: '' })
    try { const result = await createAutomationWorkflow({ ...form, interval_minutes: Number(form.interval_minutes) }); onCreated(result.workflow) }
    catch (error) { setState({ status: 'error', message: error.message }) }
  }
  return <aside className="automation-builder" aria-label="Buat workflow"><div className="config-panel__header"><div><span>Workflow builder</span><h2>Buat otomasi</h2><p>Susun trigger dan aksi dengan approval yang eksplisit.</p></div><button className="icon-button" onClick={onClose} aria-label="Tutup workflow builder"><X /></button></div>
    <div className="workflow-preview"><span><CalendarClock size={17} />Trigger</span><ChevronRight /><span><Zap size={17} />Action</span><ChevronRight /><span><ShieldCheck size={17} />Approval</span><ChevronRight /><span><Check size={17} />Result</span></div>
    <form className="upload-form" onSubmit={submit}><label className="form-field"><span>Nama workflow</span><input required minLength="3" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Contoh: Audit knowledge mingguan" /></label><label className="form-field"><span>Action</span><select value={form.action} onChange={(e) => setForm({ ...form, action: e.target.value })}><option value="knowledge_health_check">Pemeriksaan knowledge index</option><option value="learning_cycle">Siklus pembelajaran agent</option></select></label><label className="form-field"><span>Interval</span><select value={form.interval_minutes} onChange={(e) => setForm({ ...form, interval_minutes: e.target.value })}><option value="30">Setiap 30 menit</option><option value="60">Setiap jam</option><option value="1440">Setiap hari</option><option value="10080">Setiap minggu</option></select></label><label className="approval-choice"><input type="checkbox" checked={form.approval_required} onChange={(e) => setForm({ ...form, approval_required: e.target.checked })} /><span><strong>Wajib approval manusia</strong><small>Run berhenti sebelum action sampai engineer menyetujui.</small></span></label>{state.message ? <div className="upload-message upload-message--error"><CircleAlert size={17} />{state.message}</div> : null}<button className="button button--primary" disabled={state.status === 'saving'}>{state.status === 'saving' ? 'Menyimpan...' : 'Simpan workflow'}</button></form>
  </aside>
}

export default function AutomationWorkspace() {
  const [data, setData] = useState(EMPTY); const [status, setStatus] = useState('loading'); const [builder, setBuilder] = useState(false); const [message, setMessage] = useState('')
  function load() { const controller = new AbortController(); setStatus('loading'); getAutomationWorkspace(controller.signal).then((result) => { setData(result); setStatus('ready') }).catch((e) => { if (e.name !== 'AbortError') setStatus('error') }); return controller }
  useEffect(() => { const controller = load(); return () => controller.abort() }, [])
  async function toggle(item) { await setAutomationEnabled(item.id, !item.enabled); load() }
  async function run(item) { try { const result = await runAutomation(item.id); setMessage(result.run.status === 'WAITING_APPROVAL' ? 'Run dibuat dan menunggu approval engineer.' : 'Workflow selesai dijalankan.'); load() } catch { setMessage('Workflow gagal dimulai.') } }
  async function approve(runItem) { const name = window.prompt('Nama engineer yang menyetujui'); if (!name?.trim()) return; await approveAutomationRun(runItem.id, name.trim()); load() }
  async function retry(runItem) { await retryAutomationRun(runItem.id); load() }
  const pending = data.runs.filter((item) => item.status === 'WAITING_APPROVAL').length
  return <div className="page automation-page"><header className="page-header"><div><h1>Otomasi</h1><p>Jadwalkan pekerjaan agent dengan jejak eksekusi dan approval manusia.</p></div><button className="button button--primary" onClick={() => setBuilder(true)}><Plus size={18} />Buat otomasi</button></header>
    <section className="automation-summary"><div><Workflow size={19} /><span>Workflow</span><strong>{status === 'ready' ? data.workflows.length : '—'}</strong></div><div><Play size={19} /><span>Run tercatat</span><strong>{status === 'ready' ? data.runs.length : '—'}</strong></div><div><ShieldCheck size={19} /><span>Menunggu approval</span><strong>{status === 'ready' ? pending : '—'}</strong></div><div><Clock3 size={19} /><span>Scheduler</span><strong>Daemon lokal</strong></div></section>
    <div className="scheduler-note"><CircleAlert size={17} /><span>Jadwal disimpan, tetapi eksekusi periodik memerlukan daemon lokal <code>src/agent_cron.py</code>. Tombol Jalankan tetap tersedia dari workspace.</span></div>{message ? <div className="notice notice--success"><Check size={17} />{message}</div> : null}
    <div className="automation-grid"><section className="workflow-list-panel"><div className="section-heading"><div><h2>Workflow</h2><p>Trigger → action → approval → result</p></div><button className="icon-button" onClick={() => load()} aria-label="Muat ulang otomasi"><RefreshCw size={18} /></button></div><div className="workflow-list">{data.workflows.map((item) => <article className="workflow-row" key={item.id}><div className="workflow-row__top"><div className="workflow-symbol"><Workflow size={18} /></div><div><strong>{item.name}</strong><span>{actionNames[item.action]}</span></div><label className="mini-switch"><input type="checkbox" checked={item.enabled} onChange={() => toggle(item)} aria-label={`Aktifkan ${item.name}`} /><i /></label></div><div className="workflow-path"><span><CalendarClock size={14} />{item.interval_minutes} menit</span><ChevronRight /><span>{item.approval_required ? <ShieldCheck size={14} /> : <Zap size={14} />}{item.approval_required ? 'Approval' : 'Otomatis'}</span><button onClick={() => run(item)} disabled={!item.enabled}><Play size={14} />Jalankan</button></div></article>)}{status === 'ready' && !data.workflows.length ? <div className="automation-empty"><Workflow size={27} /><strong>Belum ada workflow</strong><span>Buat otomasi pertama untuk menghubungkan jadwal, action, dan approval.</span></div> : null}</div></section>
      <aside className="run-history"><div className="section-heading"><div><h2>Riwayat run</h2><p>Eksekusi terbaru dan statusnya.</p></div></div><div>{data.runs.map((item) => <article className="run-row" key={item.id}><div><strong>{item.workflow_name}</strong><code>{item.id}</code></div><RunStatus status={item.status} /><span>{new Date(item.created_at).toLocaleString('id-ID')}</span>{item.status === 'WAITING_APPROVAL' ? <button className="text-action" onClick={() => approve(item)}>Setujui</button> : item.status === 'FAILED' ? <button className="text-action" onClick={() => retry(item)}><RotateCcw size={13} />Ulangi</button> : null}</article>)}{status === 'ready' && !data.runs.length ? <div className="automation-empty automation-empty--small"><Clock3 size={24} /><span>Belum ada run.</span></div> : null}</div></aside></div>
    {builder ? <><button className="panel-backdrop" onClick={() => setBuilder(false)} aria-label="Tutup panel workflow" /><WorkflowBuilder onClose={() => setBuilder(false)} onCreated={() => { setBuilder(false); load() }} /></> : null}
  </div>
}
