"""Stable machine-readable fault taxonomy shared by specialist and fusion agents."""

from enum import Enum


class FaultCode(str, Enum):
    NORMAL = "NORMAL"
    UNKNOWN = "UNKNOWN"
    BEARING_DEGRADATION = "BEARING_DEGRADATION"
    BEARING_OUTER_RACE = "BEARING_OUTER_RACE"
    BEARING_INNER_RACE = "BEARING_INNER_RACE"
    BEARING_WEAR = "BEARING_WEAR"
    BEARING_OVERHEAT = "BEARING_OVERHEAT"
    ROTOR_BAR_DEGRADATION = "ROTOR_BAR_DEGRADATION"
    SHAFT_MISALIGNMENT = "SHAFT_MISALIGNMENT"
    ROTOR_UNBALANCE = "ROTOR_UNBALANCE"
    ELECTRICAL_HOTSPOT = "ELECTRICAL_HOTSPOT"
    DGA_HIGH_ENERGY_DISCHARGE = "DGA_HIGH_ENERGY_DISCHARGE"
    DGA_THERMAL_FAULT = "DGA_THERMAL_FAULT"
    DGA_PARTIAL_DISCHARGE = "DGA_PARTIAL_DISCHARGE"
    PARTIAL_DISCHARGE_ACTIVE = "PARTIAL_DISCHARGE_ACTIVE"


class MechanismTag(str, Enum):
    BEARING_DEGRADATION = "BEARING_DEGRADATION"
    ROTOR_ELECTRICAL_DEGRADATION = "ROTOR_ELECTRICAL_DEGRADATION"
    SHAFT_ALIGNMENT = "SHAFT_ALIGNMENT"
    THERMAL_ELECTRICAL = "THERMAL_ELECTRICAL"
    ELECTRICAL_DISCHARGE = "ELECTRICAL_DISCHARGE"
    INSULATION_DEGRADATION = "INSULATION_DEGRADATION"
