"""
src/chat_intent.py — Smart Intent Classifier for PPLE Agent Chat

Classifies each user query into one of four intent types so the
pipeline can conditionally fetch equipment data and run multi-agent
diagnosis only when actually needed.

Intent types
------------
EQUIPMENT_STATUS  — query about a specific asset's current or historical
                    condition; needs equipment data + multi-agent run.
CONCEPTUAL_TECH   — conceptual / standards / theory question within the
                    PDM/PLTU domain; needs knowledge-base only, no raw data.
GENERAL_CHAT      — greetings, identity, small-talk; needs no data at all.
OUT_OF_SCOPE      — completely outside PDM/PLTU/CBM domain; return early
                    with a polite redirect.

Design notes
------------
* NEVER import chatbot.py or replicate its branching logic.  Read only
  the *outputs* it has already computed: matched_equipment + rule_answer.
* Rule-based answer is always produced upstream and always forwarded to
  the LLM as rule_answer regardless of intent — this module only controls
  what *additional* data is fetched, not what rule-based logic runs.
* OUT_OF_SCOPE threshold is intentionally conservative: domain-adjacent
  topics (heat rate, generator theory, coal quality) are NOT out-of-scope.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Optional


# ---------------------------------------------------------------------------
# Keyword sets
# ---------------------------------------------------------------------------

# Any of these words in the query → definitely PDM/PLTU domain.
_DOMAIN_KEYWORDS: frozenset[str] = frozenset([
    # Equipment types
    "bfp", "cwp", "c3wp", "bc", "fan", "id fan", "pa fan", "fd fan",
    "motor", "pompa", "pump", "compressor", "kompresor", "generator",
    "boiler", "turbin", "turbine", "kondensor", "condenser",
    "trafo", "transformer", "uat", "esp", "precipitator",
    # CBM / PdM domain words
    "cbm", "pdm", "pltu", "pembangkit", "jeranjang",
    "vibrasi", "vibration", "getaran", "spektrum", "fft", "waveform",
    "mcsa", "atpol", "sideband", "unbalance", "thd", "rotor bar", "rotorbar",
    "dga", "duval", "rogers", "tdcg", "c2h2", "c2h4", "c2h6", "ch4", "h2",
    "co2",  # CO2 (gas transformer) — note: too short to match reliably alone
    "tribologi", "tribology", "oli", "pelumas", "viskositas", "tan", "wear",
    "thermal", "irt", "thermography", "hotspot", "suhu", "panas",
    "partial discharge", "isolasi", "stator", "insulation",
    "bearing", "bpfo", "bpfi", "bsf", "ftf",
    # Reliability / maintenance
    "keandalan", "reliability", "rul", "health index", "risk",
    "maintenance", "pemeliharaan", "work order", "inspeksi", "overhaul",
    "alarm", "kritis", "warning", "high", "abnormal",
    # Standards / engineering
    "iso", "ieee", "iec", "nema", "epri", "astm", "iee",
    "standar", "standard", "sop", "prosedur",
    "heat rate", "efisiensi", "coal", "batu bara",
    "kks", "plb", "puil", "nameplate",
    "eccentricity", "eksentrisitas", "dynamic", "dinamic", "alignment", "misalignment",
])

# Conceptual query signals — these strongly suggest the user wants an
# explanation, not a data status report.
_CONCEPT_SIGNALS: tuple[str, ...] = (
    "apa itu", "apakah", "apa yang dimaksud", "pengertian", "definisi",
    "jelaskan", "jelaskanlah", "bagaimana cara", "bagaimana prinsip",
    "cara kerja", "cara menghitung", "cara membaca", "cara mengukur",
    "bagaimana metode", "metode apa",
    "kenapa bisa", "mengapa", "kenapa",
    "apa penyebab", "apa dampak", "apa efek",
    "rumus", "formula", "persamaan",
    "standar apa", "berapa batas", "berapa limit", "berapa threshold",
    "contoh", "perbedaan antara", "bedanya apa",
    "teori", "prinsip dasar", "konsep",
    "how to", "what is", "explain", "describe", "gimana",
)

# GENERAL_CHAT signals — zero data needed.
_CHAT_SIGNALS: tuple[str, ...] = (
    "halo", "hai", "hi", "hey", "hei", "selamat pagi", "selamat siang",
    "selamat sore", "selamat malam", "assalamualaikum", "wassalamualaikum",
    "terima kasih", "terimakasih", "makasih", "thanks", "thank you",
    "matur nuwun", "sama-sama",
    "apa kabar", "bagaimana kabar", "gimana kabar",
    "siapa kamu", "kamu siapa", "siapa anda", "anda siapa",
    "profil", "identitas", "tentang kamu", "peranmu", "tugasmu",
    "kamu bisa apa", "namamu", "siapa namamu",
    "lagi ngapain", "sedang apa", "lagi apa",
    "mantap", "hebat", "keren", "bagus", "good job",
    "oke", "siap", "sip", "ok",
)

# Rule-answer prefixes that signal an expert conceptual explanation was
# already generated by chatbot._get_expert_concept_explanation().
_CONCEPT_RULE_PREFIXES: tuple[str, ...] = (
    "📚",          # knowledge-base doc reference
    "🔬",          # conceptual section header
    "### apa itu",
    "### definisi",
    "### konsep",
    "### standar",
    "### prinsip",
    "**apa itu",
    "**definisi",
    "definisi & konsep",
    "standar internasional",
)


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------

@dataclass
class IntentResult:
    """Classification result for a single chat query.

    Attributes
    ----------
    intent_type : str
        One of "EQUIPMENT_STATUS", "CONCEPTUAL_TECH", "GENERAL_CHAT",
        "OUT_OF_SCOPE".
    needs_equipment_data : bool
        Whether the pipeline should pass df_context / df_history to the LLM.
    needs_multi_agent : bool
        Whether the multi-agent collaborative diagnosis should run.
    domain_hint : str or None
        Detected CBM domain if discernible ("mcsa", "vibration", "dga",
        "thermal", "tribology", "pd"), else None.
    equipment_hint : str or None
        The matched equipment name forwarded from chatbot, if any.
    """

    intent_type: str = "EQUIPMENT_STATUS"
    needs_equipment_data: bool = True
    needs_multi_agent: bool = True
    domain_hint: Optional[str] = None
    equipment_hint: Optional[str] = None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def classify_intent(
    query: str,
    matched_equipment: Optional[str],
    rule_answer: str,
    conversation_context: str = "",
) -> IntentResult:
    """Classify a user query into one of four intent categories.

    Parameters
    ----------
    query : str
        Raw user message text.
    matched_equipment : str or None
        Equipment name matched by MCSAChatbot.match_equipment(), or None.
    rule_answer : str
        Rule-based answer already produced by MCSAChatbot.process_query().
    conversation_context : str
        History of the conversation session to provide context for short follow-ups.

    Returns
    -------
    IntentResult
        Classification with pipeline-control flags.
    """
    q = (query or "").strip()
    q_lower = q.lower()
    rule_lower = (rule_answer or "").strip().lower()
    conv_lower = (conversation_context or "").strip().lower()

    # ------------------------------------------------------------------
    # 1. GENERAL_CHAT — check first; these need no data at all.
    # ------------------------------------------------------------------
    if _is_general_chat(q_lower):
        return IntentResult(
            intent_type="GENERAL_CHAT",
            needs_equipment_data=False,
            needs_multi_agent=False,
            domain_hint=None,
            equipment_hint=matched_equipment,
        )

    # ------------------------------------------------------------------
    # 2. EQUIPMENT_STATUS — if chatbot already matched an equipment name,
    #    or if query combines a status keyword with a piece of machinery.
    # ------------------------------------------------------------------
    if matched_equipment:
        return IntentResult(
            intent_type="EQUIPMENT_STATUS",
            needs_equipment_data=True,
            needs_multi_agent=True,
            domain_hint=_detect_domain(q_lower),
            equipment_hint=matched_equipment,
        )

    # Status-seeking keywords that imply live data is wanted.
    _STATUS_KEYWORDS = (
        "kondisi", "status", "diagnosa", "diagnosis", "analisa", "analisis",
        "histori", "riwayat", "kronologi", "tren", "hasil", "data",
        "nilai", "pengukuran", "measurement", "laporan", "report",
        "alarm", "warning", "kritis", "high", "alert",
        "berapa", "berapa nilainya", "berapa sekarang",
        "apa hasilnya", "apa kondisinya",
    )
    if any(kw in q_lower for kw in _STATUS_KEYWORDS) and _is_in_domain(q_lower):
        return IntentResult(
            intent_type="EQUIPMENT_STATUS",
            needs_equipment_data=True,
            needs_multi_agent=False,   # no specific equipment → skip multi-agent
            domain_hint=_detect_domain(q_lower),
            equipment_hint=None,
        )

    # ------------------------------------------------------------------
    # 3. OUT_OF_SCOPE — no PDM/PLTU domain keyword at all.
    # ------------------------------------------------------------------
    if not _is_in_domain(q_lower):
        # Allow very short queries to fall through (greetings that didn't
        # match _CHAT_SIGNALS exactly, single-word questions, etc.)
        if len(q_lower.split()) > 4:
            return IntentResult(
                intent_type="OUT_OF_SCOPE",
                needs_equipment_data=False,
                needs_multi_agent=False,
                domain_hint=None,
                equipment_hint=None,
            )

    # ------------------------------------------------------------------
    # 4. CONCEPTUAL_TECH — in-domain but asking for explanation/theory.
    # ------------------------------------------------------------------
    if _is_conceptual(q_lower, rule_lower, conv_lower):
        return IntentResult(
            intent_type="CONCEPTUAL_TECH",
            needs_equipment_data=False,
            needs_multi_agent=False,
            domain_hint=_detect_domain(q_lower),
            equipment_hint=None,
        )

    # ------------------------------------------------------------------
    # 5. Default: treat as EQUIPMENT_STATUS (data query) but without a
    #    specific equipment → multi-agent won't run anyway (no matched_eq).
    # ------------------------------------------------------------------
    return IntentResult(
        intent_type="EQUIPMENT_STATUS",
        needs_equipment_data=True,
        needs_multi_agent=False,
        domain_hint=_detect_domain(q_lower),
        equipment_hint=None,
    )


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _is_general_chat(q_lower: str) -> bool:
    """True when query is purely social / identity / pleasantries."""
    # For single-word signals (≤ 6 chars), require whole-word match to avoid
    # substring false positives (e.g. 'sip' inside 'siapakah', 'ok' inside 'oke').
    import re as _re
    for sig in _CHAT_SIGNALS:
        if " " in sig:
            # Multi-word signal — substring match is safe (unlikely to appear in
            # technical queries by accident).
            if sig in q_lower:
                return True
        else:
            # Single-word signal — whole-word match only.
            if _re.search(r"\b" + _re.escape(sig) + r"\b", q_lower):
                return True
    # Very short pure greeting-like message (≤ 3 words, no domain keyword)
    words = q_lower.split()
    if len(words) <= 3 and not _is_in_domain(q_lower):
        return True
    return False


def _is_in_domain(q_lower: str) -> bool:
    """True when the query contains at least one PDM/PLTU domain keyword."""
    for kw in _DOMAIN_KEYWORDS:
        if kw in q_lower:
            return True
    return False


def _is_conceptual(q_lower: str, rule_lower: str, conv_lower: str = "") -> bool:
    """True when query is asking for an explanation rather than a data status."""
    # Direct concept-signal match in the user's question
    if any(sig in q_lower for sig in _CONCEPT_SIGNALS):
        return True

    # If it's a short question that implies continuation ("kalau X?", "terus Y?")
    is_follow_up_style = len(q_lower.split()) <= 6 or any(q_lower.startswith(w) for w in ("kalau", "terus", "bagaimana dengan"))
    if is_follow_up_style and conv_lower:
        # If the history contains domain keywords, and the user's short question
        # contains a domain keyword, it's likely a continuation of a conceptual discussion.
        if _is_in_domain(conv_lower) and _is_in_domain(q_lower):
            return True

    # Rule answer already structured as a conceptual explanation
    for prefix in _CONCEPT_RULE_PREFIXES:
        if rule_lower.startswith(prefix.lower()):
            return True

    # Rule answer contains knowledge-base reference header
    if "referensi & panduan teknis" in rule_lower or "📚" in rule_lower:
        return True

    return False


def _detect_domain(q_lower: str) -> Optional[str]:
    """Best-effort domain hint from query keywords."""
    if any(k in q_lower for k in ("vibrasi", "vibration", "getaran", "spektrum", "iso 10816", "bpfo", "bpfi", "unbalance", "misalign")):
        return "vibration"
    if any(k in q_lower for k in ("dga", "duval", "rogers", "tdcg", "c2h2", "c2h4", "c2h6", "ch4", "minyak trafo", "gas trafo")):
        return "dga"
    if any(k in q_lower for k in ("mcsa", "atpol", "sideband", "rotor bar", "rotorbar", "unbalance arus", "thd", "harmonik")):
        return "mcsa"
    if any(k in q_lower for k in ("thermal", "irt", "thermography", "hotspot", "delta-t", "suhu", "panas")):
        return "thermal"
    if any(k in q_lower for k in ("tribologi", "tribology", "oli", "pelumas", "viskositas", "tan", "keausan", "wear")):
        return "tribology"
    if any(k in q_lower for k in ("partial discharge", "pd", "isolasi", "stator", "prpd", "insulation", "corona")):
        return "pd"
    return None
