"""Core Work Orders data store and operations.

Provides persistent storage (JSON-backed, configurable via WORK_ORDERS_FILE env var),
seeding, loading, saving, and status workflow transitions for Work Orders generated by
CBM Multi-Agent or created manually by maintenance engineers.
"""

from __future__ import annotations

import json
import os
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

from src.data_loader import get_data_path

_work_orders_db: List[Dict[str, Any]] = []


def seed_work_orders() -> List[Dict[str, Any]]:
    """Default seed work orders for demonstration."""
    return [
        {
            "wo_number": "WO-202608-0101",
            "equipment": "BC 10.1",
            "title": "Investigasi Bearing & Re-greasing DE/NDE",
            "priority": "P2 - High",
            "reason": "AI Multi-Modal Fusion: Indikasi keausan bearing & suhu naik",
            "required_tools": ["Vibration Analyzer", "Thermal Camera", "Grease Gun"],
            "required_parts": ["Grease Shell Gadus S2", "Bearing 6314 C3"],
            "required_manpower": "2 Technicians",
            "target_completion_date": "2026-08-30",
            "status": "Draft - Awaiting Approval",
            "created_at": "2026-08-15 08:30",
            "created_by": "CBM Fusion Agent",
        },
        {
            "wo_number": "WO-202608-0102",
            "equipment": "BFP 1A",
            "title": "Laser Alignment Verification & Soft Foot Check",
            "priority": "P3 - Medium",
            "reason": "AI Diagnostics: Modulasi spektrum 2X & getaran aksial",
            "required_tools": ["Laser Alignment Kit", "Dial Indicator"],
            "required_parts": ["Stainless Steel Shim Pack 0.05-1.0mm"],
            "required_manpower": "1 Alignment Specialist + 1 Mechanic",
            "target_completion_date": "2026-09-05",
            "status": "Approved - Ready for Execution",
            "created_at": "2026-08-18 10:15",
            "created_by": "Vibration Agent",
        },
        {
            "wo_number": "WO-202609-0103",
            "equipment": "CWP 1A",
            "title": "Sampling Ulang Minyak Pelumas & Cek Kadar Air",
            "priority": "P3 - Medium",
            "reason": "Tribology Agent: Partikel wear Fe naik dan viskositas sedikit deviasi",
            "required_tools": ["Oil Sampling Bottle Kit", "Vacuum Pump Sampler"],
            "required_parts": ["Sample Bottle 250ml", "ID Label"],
            "required_manpower": "1 Lubrication Tech",
            "target_completion_date": "2026-09-15",
            "status": "In Progress",
            "created_at": "2026-09-01 09:00",
            "created_by": "Tribology Agent",
        },
        {
            "wo_number": "WO-202609-0104",
            "equipment": "TR-01 Unit 1",
            "title": "Inspeksi Bushing & Pengukuran Ulang DGA (Duval Triangle T2)",
            "priority": "P1 - Critical",
            "reason": "DGA Agent: Gas asetilena (C2H2) terdeteksi di atas threshold aman",
            "required_tools": ["Syringe DGA 50ml", "IR Thermography"],
            "required_parts": ["Seal Kit Bushing"],
            "required_manpower": "2 Electrical Engineers",
            "target_completion_date": "2026-09-12",
            "status": "Draft - Awaiting Approval",
            "created_at": "2026-09-08 14:20",
            "created_by": "DGA Agent",
        },
    ]


def get_work_orders_store_path() -> str:
    """Resolve destination JSON path for work orders persistence."""
    configured = os.environ.get("WORK_ORDERS_FILE")
    if configured and configured.strip():
        return os.path.abspath(configured.strip())
    return get_data_path("runtime", "work_orders.json")


def load_work_orders() -> List[Dict[str, Any]]:
    """Load work orders from persistent JSON storage, fallback to seed if empty."""
    global _work_orders_db
    path = get_work_orders_store_path()
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as fp:
                data = json.load(fp)
            if isinstance(data, list) and data:
                _work_orders_db = data
                return data
        except Exception:
            pass

    _work_orders_db = seed_work_orders()
    try:
        save_work_orders(_work_orders_db)
    except Exception:
        pass
    return list(_work_orders_db)


def save_work_orders(work_orders: List[Dict[str, Any]]) -> str:
    """Atomic write of work orders list to JSON storage."""
    global _work_orders_db
    path = get_work_orders_store_path()
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp_path = path + ".tmp"
    with open(tmp_path, "w", encoding="utf-8") as fp:
        json.dump(work_orders, fp, ensure_ascii=False, indent=2)
    os.replace(tmp_path, path)
    _work_orders_db = list(work_orders)
    return path


def create_work_order(
    equipment: str,
    title: str,
    priority: str = "P3 - Medium",
    reason: str = "",
    required_tools: Optional[List[str]] = None,
    required_parts: Optional[List[str]] = None,
    required_manpower: str = "1 Technician",
    target_completion_date: str = "",
    created_by: str = "Maintenance Engineer",
) -> Dict[str, Any]:
    """Create and append a new Work Order."""
    orders = load_work_orders()
    now = datetime.now()
    wo_number = f"WO-{now.strftime('%Y%m')}-{uuid.uuid4().hex[:4].upper()}"

    new_wo = {
        "wo_number": wo_number,
        "equipment": equipment.strip(),
        "title": title.strip(),
        "priority": priority,
        "reason": reason.strip(),
        "required_tools": required_tools or [],
        "required_parts": required_parts or [],
        "required_manpower": required_manpower,
        "target_completion_date": target_completion_date or (now.strftime("%Y-%m-%d")),
        "status": "Draft - Awaiting Approval",
        "created_at": now.strftime("%Y-%m-%d %H:%M"),
        "created_by": created_by,
    }

    orders.insert(0, new_wo)
    save_work_orders(orders)
    return new_wo


def update_work_order_status(
    wo_number: str,
    action: str,
    actor: str = "Supervisor",
) -> Optional[Dict[str, Any]]:
    """Transition work order status based on action: Approve, Progress, Complete, Reject."""
    orders = load_work_orders()
    for wo in orders:
        if wo.get("wo_number") == wo_number:
            if action == "Approve":
                wo["status"] = f"Approved by {actor} - Ready for Execution"
            elif action == "Progress":
                wo["status"] = f"In Progress ({actor})"
            elif action == "Complete":
                wo["status"] = f"Completed & Closed by {actor}"
            elif action == "Reject":
                wo["status"] = f"Rejected by {actor}"
            save_work_orders(orders)
            return wo
    return None
